.PHONY: clean All

All:
	@echo "----------Building project:[ PEC1 - Debug ]----------"
	@cd "PEC1" && "$(MAKE)" -f  "PEC1.mk"
clean:
	@echo "----------Cleaning project:[ PEC1 - Debug ]----------"
	@cd "PEC1" && "$(MAKE)" -f  "PEC1.mk" clean
